# Generated by Django 2.2.16 on 2020-09-01 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reset_network_partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resetnetworkpartnerspage',
            options={'verbose_name': 'Reset Network Partners Page'},
        ),
    ]
