# Generated by Django 2.2.16 on 2020-09-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reset_network_partner', '0002_auto_20200901_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resetnetworkpartnerpage',
            options={'verbose_name': 'Reset Network Partner Page'},
        ),
        migrations.RemoveField(
            model_name='resetnetworkpartnerpage',
            name='url',
        ),
        migrations.AddField(
            model_name='resetnetworkpartnerpage',
            name='web_url',
            field=models.URLField(blank=True),
        ),
    ]
