# Generated by Django 2.2.16 on 2020-09-01 19:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import hypha.reset_network.reset_network_partner.models


class Migration(migrations.Migration):

    dependencies = [
        ('reset_network_partner', '0003_auto_20200901_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetNetworkInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('primary_impact_area', models.CharField(choices=[('civic_empowerment', 'Civic Empowerment'), ('data_and_digital_rights', 'Data & Digital Rights'), ('financial_transparency', 'Financial Transparency'), ('independent_media', 'Independent Media'), ('reset', 'Reset'), ('other', 'Other')], default='', max_length=50)),
                ('geographic_focus', models.CharField(choices=[('africa', 'Africa'), ('central_and_eastern_europe', 'Central And Eastern Europe'), ('global', 'Global'), ('latin_america', 'Latin America'), ('multi_country', 'Multi-Country'), ('southeast_asia', 'Southeast Asia'), ('united_states', 'United States'), ('western_europe', 'Western Europe'), ('other', 'Other')], default='', max_length=50)),
                ('year', models.IntegerField(default=hypha.reset_network.reset_network_partner.models.current_year, help_text='Use format: <YYYY>', validators=[django.core.validators.MinValueValidator(1984), hypha.reset_network.reset_network_partner.models.max_value_current_year])),
                ('amount_committed', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('type', models.CharField(blank=True, max_length=200)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='reset_network_partner.ResetNetworkPartnerPage')),
            ],
        ),
    ]
