# Generated by Django 2.2.16 on 2020-09-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reset_network_partner', '0004_resetnetworkinvestment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetnetworkinvestment',
            name='amount_committed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Ammount Commited US$'),
        ),
    ]
